### ISSUE TITLE
How to use/depend on this formula

### ISSUE THREAD

**Issue by bradenwright** [tcpcloud/salt-formula-jenkins#34]
I was able to successfully use this repo with .kitchen.yml:

```
cat .kitchen.yml
---
driver:
  name: docker
  use_sudo: false
  privileged: true

verifier:
  name: inspec
  format: doc

provisioner:
  name: salt_solo
  require_chef: false
  formula: sh-jenkins
  is_file_root: true
  cpu: 1024
  memory: 2G
  forward:
  - 8081:8080
  dependencies:
    - name: java
      repo: git
      source: https://github.com/tcpcloud/salt-formula-java
    - name: jenkins
      repo: git
      source: https://github.com/salt-formulas/salt-formula-jenkins
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8 && apt-get install -y git
      run_command: /sbin/init
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: sh_jenkins_master
    provisioner:
      state_top:
        base:
          '*':
            - sh-jenkins
      pillars:
        top.sls:
          base:
            '*':
              - sh-jenkins
        sh-jenkins.sls:
          jenkins:
            master:
              enabled: true
              mode: EXCLUSIVE
              # Do not manage config.xml from Salt, use UI instead
              no_config: true
              http:
                network: any
                port: 8080
                protocol: http
              user:
                admin:
                  password: password
                  email: root@domain.com
              plugins:
                - name: slack
                - name: rebuild
          linux:
            system:
              enabled: true
              repo:
                jenkins:
                  enabled: true
                  source: "deb http://pkg.jenkins.io/debian-stable binary/"
                  key_url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
          java:
            environment:
              enabled: true
              version: '8'
              platform: openjdk
              development: true
```

Since the dependencies is using a git repo for https://github.com/salt-formulas/salt-formula-jenkins everything seems to work.  When I looked up how to use dependencies on salt master I came across:

https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html

which says "We strongly recommend forking a formula repository into your own GitHub account to avoid unexpected changes to your infrastructure." I tried to clone that down into my own folder structure but I can't get things to work... b/c everything is in a sub-directory so I had to change formulas to include 'jenkins.jenkins.master', this hack got me most the way but it can't leverage the module: https://github.com/salt-formulas/salt-formula-jenkins/blob/master/_modules/jenkins_common.py#L140

This is causing pillar data for encrypted password to not be set and formula blows up.

Can someone point me in the right direction for salt best practice on config/how to clone public repos down and leverage them in my own custom Salt formulas.

I know this isn't necessarily an issue with this repo, but hoping I can get some guidance.

Thanks in advance for any help

**Comment by bradenwright** [comment]
Forgot to add, I have tried to follow: https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#adding-a-formula-directory-manually

git clone to setup:
```
$ ls /srv/salt-public-formulas/
salt-formula-java  salt-formula-jenkins  salt-formula-linux
```

```
file_roots:
  base:
    - /srv/salt/
    - /srv/salt-public-formulas/salt-formula-java
    - /srv/salt-public-formulas/salt-formula-jenkins
    - /srv/salt-public-formulas/salt-formula-linux
```

and restart salt master.  Still getting the following error:

```
----------
          ID: /var/lib/jenkins/users/admin/config.xml
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'jenkins_common.encode_password'
     Started: 23:36:17.034939
    Duration: 186.838 ms
     Changes:   
----------
```

which (as mentioned above) seems to be b/c it can't access https://github.com/salt-formulas/salt-formula-jenkins/blob/master/_modules/jenkins_common.py#L140
