### ISSUE TITLE
java_packages required?

### ISSUE THREAD

**Issue by dalvizu** [tcpcloud/salt-formula-jenkins#36]
I'm trying to use this formula and seeing this error:

```
       local:
       ----------
                 ID: jenkins_packages
           Function: pkg.installed
               Name: jenkins
             Result: False
            Comment: The following requisites were not found:
                                 require:
                                     pkg: java_packages
```

This seems to imply a dependency on java_packages package being installed -- I can't find any documentation on this though. What am I supposed to be defining?

**Comment by fpytloun** [comment]
This resource is provided by salt-formula-java which should be a dependency of this one.
In theory this dependency should not be needed as jenkins package should already depend on java packages.
If you try to use this formula without salt-formula-java, please submit pull request if you succeed. Otherwise use java formula to setup java environment.

**Comment by dalvizu** [comment]
I've tested this on ubuntu 16.04 and latest Jenkins, and java 8 is a requirement on the debian package and is installed. I've uncovered an additional dependency - the debian repo is not included, and I had to install it using the 'salt-formula-linux' formula (salt-formulas/salt-formula-linux) with these pillars:

```
linux:
  system:
    enabled: true
    repo:
      jenkins:
        enabled: true
        source: "deb http://pkg.jenkins.io/debian-stable binary/"
        key_url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
```

I am new to formula so I do not know how to manage this - should I just add documentation, or is this something that needs to be built into the formula?
